locale:
    path: /
    defaults: {_controller: AppBundle:Page:locale}

post_show:
    path: /post/{id}
    defaults: {_controller: AppBundle:Post:show}
    options:
        expose: true

post_edit:
    path: /post/{id}/edit
    defaults: {_controller: AppBundle:Post:edit}
    options:
        expose: true

app:
    resource: "@AppBundle/Controller/"
    prefix: /{_locale}
    type: annotation
    requirements:
        _locale: en|de

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
